### ISSUE TITLE
Series 1 Actives/inactives

### ISSUE THREAD

**Issue by mattodd** [OpenSourceTB/OpenSourceTB_To_Do_List#2]
Hi @jessicabaiget We had some interest from someone in doing some mechanism of action work on Series 1. Do you have all the samples from your syntheses (http://openwetware.org/wiki/OpenSourceTB:OSTB_Series_1#Project_3) in Tres Cantos? We could use a few mgs of two actives and two inactives. OSTBS24 and 25 are perfect, for example - very different in potency but similar in structure. Is there another pair of compounds like this we could send off - i.e. that you have to hand and which are still in good condition?

**Comment by mattodd** [comment]
Confirming that the person running the assay is happy to receive the compounds - so my sense is that we need two actives and two inactives that are in pairs that are ideally structurally similar, between 2 and five milligrams each compound. Do you have an idea for which compounds we have available for this? We'd need to ship to New Zealand.

**Comment by jessicabaiget** [comment]
Hi @mattodd 
I checked in LabArchives if we have samples for some of these compounds, as I used quite a lot to get full characterisation at that time.  We should have for all of them except OSTBS25. The Series 1 compounds are in the University of Sydney, and they should be checked if they are still in good conditions by a quick NMR or HPLC, because sadly they are not very stable...

**Comment by mattodd** [comment]
OK, so.. which compounds should we send? :)

**Comment by mattodd** [comment]
Closing following establishment of dedicated Series 1 repo. MoA studies can be discussed further there.
